server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user_registration
    username: root
    password: Les4eclairs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
